const quizType = {
  CREATED_QUIZZES: 'CREATED_QUIZZES',
  PAST_CREATED_QUIZZES: 'PAST_CREATED_QUIZZES',
  ENTERED_QUIZZES: 'ENTERED_QUIZZES',
  PAST_ENTERED_QUIZZES: 'PAST_ENTERED_QUIZZES',
};

const timerType = {
  TIME_TO_START: 'TIME_TO_START',
  TIME_TO_ANSWER: 'TIME_TO_ANSWER',
  TIME_TO_FREEZE_ANSWER: 'TIME_TO_FREEZE_ANSWER',
};

export default { quizType, timerType };
